export const POSTS = "POSTS";
export const POSTS_SUCCESS = "POSTS_SUCCESS";
export const POSTS_FAILURE = "POSTS_FAILURE";

export const CURRENT_PAGE = "CURRENT_PAGE";
export const CURRENT_PAGE_SUCCESS = "CURRENT_PAGE_SUCCESS";
export const CURRENT_PAGE_FAILURE = "CURRENT_PAGE_FAILURE";

export const POSTS_PER_PAGE = "POSTS_PER_PAGE";
export const POSTS_PER_PAGE_SUCCESS = "POSTS_PER_PAGE_SUCCESS";
export const POSTS_PER_PAGE_FAILURE = "POSTS_PER_PAGE_FAILURE";

export const FILTERED_POSTS = "FILTERED_POSTS";
export const FILTERED_POSTS_SUCCESS = "FILTERED_POSTS_SUCCESS";
export const FILTERED_POSTS_FAILURE = "FILTERED_POSTS_FAILURE";
